name: Tests

on: [ push,pull_request ]

jobs:
  uneditable:
    uses: esplora/.github/.github/workflows/phpunit-for-laravel.yaml@main
    with:
      os: '[ "ubuntu-latest", "windows-latest", "macos-latest" ]'
      php: '[ "8.3", "8.2", "8.1", "8.0" ]'
      laravel: '[ "11.*", "10.*", "9.*" ]'
      include: '[{"laravel":"11.*", "testbench": "9.*"}, {"laravel":"10.*", "testbench": "8.*"}, {"laravel":"9.*", "testbench": "7.*"}]'
      execute: '[{"laravel":"11.*", "php":"8.0"}, {"laravel":"11.*", "php":"8.1"}, {"laravel":"10.*", "php":"8.0"}]'
      use-redis: false
